


using Blazm.Bluetooth;
using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;
using SharpGPX;
using SharpGPX.GPX1_1;
using System.Text;

namespace VariaLogger.Pages
{
	public partial class Download
	{
		public async Task OnClickDownloadViaHttpClientButton()
		{
			var trkpt = new wptTypeCollection();
			foreach (var p in StateContainer.PositionHistory)
			{
				wptType wpt = new(p.Coords.Latitude, p.Coords.Longitude, p.Coords.Altitude, DateTimeOffset.FromUnixTimeMilliseconds(p.Timestamp).UtcDateTime);
				trkpt.Add(wpt);
			}

			var filename = trkpt[0].time.ToString();

			GpxClass track = new GpxClass()
			{
				Metadata = new metadataType()
				{
					author = new personType("ers", "erik@steini.at"),
					name = "Test Track",
					desc = "Test track generated by Varialogger",
				},
			};

			track.Tracks.Add(new trkType()
			{
				name = DateTime.Now.ToString(),
				trkseg = new trksegTypeCollection().AddItem(
					new trksegType()
					{
						trkpt = trkpt
					})
			});

			track.Metadata.bounds = track.GetBounds();

			var bytes = Encoding.UTF8.GetBytes(track.ToXml());

			await JSRuntime.InvokeVoidAsync(
				"downloadFromByteArray",
				new
				{
					ByteArray = bytes,
					FileName = filename + ".gpx",
					ContentType = "application/gpx+xml"
				});
		}
	}
}